### ISSUE TITLE
Result of 7 years of research

### ISSUE THREAD

**Issue by szepeviktor** [luizbills/wp-plugin-base#22]
Hello @luizbills!

🧠  the contents of my brain :)

- plugin template: https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md
- WordPress installation template: https://github.com/szepeviktor/composer-managed-wordpress

I hope you will like it.

**Comment by luizbills** [comment]
Hi @szepeviktor thanks!! 
I have to admit that I had already taken a look at your small-project repository :smile: 
Take care!
